# Development Docker Compose - PostgreSQL Only
#
# Start PostgreSQL for local development:
#   docker compose -f docker-compose.dev.yml up -d
#
# Stop database:
#   docker compose -f docker-compose.dev.yml down
#
# Stop and remove volumes (WARNING: deletes all data):
#   docker compose -f docker-compose.dev.yml down -v

services:
  postgres:
    image: postgres:16-alpine
    container_name: llmbattler-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: llmbattler
      POSTGRES_INITDB_ARGS: "-E UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: llmbattler_postgres_data
